# To run use the:
# docker build -t voice-calculator-back-end -f docker/dockerfile .
# docker run -p 7860:7860 voice-calculator-back-end
# Use the official Python image from the Docker Hub
FROM python:3.11-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements file if you have one
COPY requirements.txt .

# Install the dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port the app runs on
EXPOSE 7860
ENV GRADIO_SERVER_NAME="0.0.0.0"

# Copy the rest of the application code to the container
COPY . .

# Run the tests using pytest
CMD ["python", "src/main_example.py"]